-- ONEFIX / esquema inicial de PostgreSQL.
-- Solo para una base nueva y vacía. No importa ni mezcla los registros de la beta.
-- Los importes conservan DOUBLE PRECISION del prototipo; validar NUMERIC antes de producción.

CREATE TABLE IF NOT EXISTS payrolls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "weekStart" TEXT NOT NULL UNIQUE,
  "weekEnd" TEXT NOT NULL,
  status TEXT NOT NULL,
  "submittedAt" TEXT NOT NULL,
  "reviewedAt" TEXT,
  "approvedAt" TEXT,
  note TEXT NOT NULL DEFAULT '',
  "reviewedBy" INTEGER,
  "approvedBy" INTEGER
);

CREATE TABLE IF NOT EXISTS people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  kind TEXT NOT NULL,
  "jobTitle" TEXT NOT NULL DEFAULT '',
  document TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  "receiptChannel" TEXT NOT NULL DEFAULT 'auto',
  bank TEXT NOT NULL,
  account TEXT NOT NULL,
  "payType" TEXT NOT NULL,
  rate DOUBLE PRECISION NOT NULL,
  "overtimeRate" DOUBLE PRECISION,
  "overtimeEnabled" INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS people_document_ci_unique ON people (lower(document));

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS contracts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT NOT NULL UNIQUE,
  "personId" INTEGER NOT NULL REFERENCES people(id),
  "projectId" INTEGER NOT NULL REFERENCES projects(id),
  description TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  "authorizedAmount" DOUBLE PRECISION NOT NULL,
  date TEXT NOT NULL,
  notes TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS amendments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contractId" INTEGER NOT NULL REFERENCES contracts(id),
  delta DOUBLE PRECISION NOT NULL,
  note TEXT NOT NULL,
  date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personId" INTEGER NOT NULL REFERENCES people(id),
  "projectId" INTEGER NOT NULL REFERENCES projects(id),
  "contractId" INTEGER REFERENCES contracts(id),
  description TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  date TEXT NOT NULL,
  approved INTEGER NOT NULL DEFAULT 0,
  "payrollId" INTEGER REFERENCES payrolls(id)
);

CREATE TABLE IF NOT EXISTS attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personId" INTEGER NOT NULL REFERENCES people(id),
  date TEXT NOT NULL,
  hours DOUBLE PRECISION NOT NULL,
  overtime DOUBLE PRECISION NOT NULL,
  absent INTEGER NOT NULL,
  bonus DOUBLE PRECISION NOT NULL,
  note TEXT NOT NULL,
  "projectName" TEXT NOT NULL DEFAULT '',
  responsible TEXT NOT NULL DEFAULT '',
  "timeIn" TEXT NOT NULL DEFAULT '',
  "timeOut" TEXT NOT NULL DEFAULT '',
  "breakMinutes" INTEGER NOT NULL DEFAULT 0,
  allocations TEXT,
  revision INTEGER NOT NULL DEFAULT 1,
  UNIQUE ("personId", date)
);

CREATE TABLE IF NOT EXISTS deductions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personId" INTEGER NOT NULL REFERENCES people(id),
  kind TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  date TEXT NOT NULL,
  note TEXT NOT NULL,
  photo TEXT,
  manager TEXT NOT NULL,
  applied DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payroll_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payrollId" INTEGER NOT NULL REFERENCES payrolls(id),
  "personId" INTEGER NOT NULL REFERENCES people(id),
  "personName" TEXT NOT NULL,
  kind TEXT NOT NULL,
  "jobTitle" TEXT NOT NULL DEFAULT '',
  gross DOUBLE PRECISION NOT NULL,
  deductions DOUBLE PRECISION NOT NULL,
  net DOUBLE PRECISION NOT NULL,
  details TEXT NOT NULL,
  observation TEXT NOT NULL DEFAULT '',
  allocations TEXT NOT NULL,
  "projectAllocations" TEXT,
  "attendanceSnapshot" TEXT,
  paid INTEGER NOT NULL DEFAULT 0,
  "paidAt" TEXT,
  method TEXT,
  reference TEXT,
  reviewed INTEGER NOT NULL DEFAULT 0,
  "reviewedAt" TEXT,
  "reviewedBy" INTEGER,
  UNIQUE ("payrollId", "personId")
);

CREATE TABLE IF NOT EXISTS payment_events (
  "operationId" TEXT PRIMARY KEY,
  "lineId" INTEGER NOT NULL REFERENCES payroll_lines(id),
  "userId" INTEGER NOT NULL,
  method TEXT NOT NULL,
  reference TEXT NOT NULL,
  "recordedAt" TEXT NOT NULL,
  "syncedAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS receipt_deliveries (
  id BIGSERIAL PRIMARY KEY,
  "lineId" INTEGER NOT NULL UNIQUE REFERENCES payroll_lines(id),
  channel TEXT NOT NULL CHECK (channel IN ('email','whatsapp','none')),
  destination TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK (status IN ('pending','configuration','missing_contact','sending','accepted','failed','verify')),
  attempts INTEGER NOT NULL DEFAULT 0,
  "providerId" TEXT,
  "lastError" TEXT NOT NULL DEFAULT '',
  "attemptedAt" TIMESTAMPTZ,
  "acceptedAt" TIMESTAMPTZ,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payroll_revisions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "originalId" INTEGER NOT NULL,
  "weekStart" TEXT NOT NULL,
  snapshot TEXT NOT NULL,
  "withdrawnBy" INTEGER NOT NULL,
  "withdrawnAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll_absence_adjustments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personId" INTEGER NOT NULL REFERENCES people(id),
  "weekStart" TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  "updatedBy" INTEGER NOT NULL,
  "updatedAt" TEXT NOT NULL,
  UNIQUE ("personId", "weekStart")
);

CREATE TABLE IF NOT EXISTS daily_pays (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attendanceId" INTEGER NOT NULL UNIQUE REFERENCES attendance(id),
  "proposedAmount" DOUBLE PRECISION NOT NULL,
  "approvedAmount" DOUBLE PRECISION,
  note TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  "confirmedBy" INTEGER,
  "confirmedAt" TEXT
);

CREATE TABLE IF NOT EXISTS app_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  "createdAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance_conflicts (
  "operationId" TEXT PRIMARY KEY,
  "personId" INTEGER NOT NULL REFERENCES people(id),
  date TEXT NOT NULL,
  "expectedRevision" INTEGER NOT NULL,
  "currentRevision" INTEGER NOT NULL,
  proposed TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT 'version',
  "submittedBy" INTEGER NOT NULL REFERENCES app_users(id),
  "submittedAt" TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  "resolvedBy" INTEGER REFERENCES app_users(id),
  "resolvedAt" TEXT
);

CREATE TABLE IF NOT EXISTS app_sessions (
  "tokenHash" TEXT PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES app_users(id),
  "expiresAt" BIGINT NOT NULL,
  demo INTEGER NOT NULL DEFAULT 0,
  "demoCredentialHash" TEXT
);

CREATE TABLE IF NOT EXISTS app_invites (
  "tokenHash" TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  role TEXT NOT NULL,
  "expiresAt" BIGINT NOT NULL,
  "createdBy" INTEGER NOT NULL REFERENCES app_users(id)
);

CREATE TABLE IF NOT EXISTS app_downloads (
  "tokenHash" TEXT PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES app_users(id),
  path TEXT NOT NULL,
  "expiresAt" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES app_users(id),
  action TEXT NOT NULL,
  target TEXT NOT NULL,
  "createdAt" TEXT NOT NULL
);
